given is experimental at /var/spool/gridengine/execd/mblade1308/job_scripts/2362579 line 18.

Starting "/usr/autodesk/maya2020/bin/maya"
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/2362579.1.long.q/runtime-cwang85'
Warning: file: /home/cwang85/maya/2020/prefs/filePathEditorRegistryPrefs.mel line 4: filePathEditor: Attribute 'aiImage.filename' is invalid or is not designated 'usedAsFilename'.
Warning: file: /home/cwang85/maya/2020/prefs/filePathEditorRegistryPrefs.mel line 5: filePathEditor: Attribute 'aiPhotometricLight.aiFilename' is invalid or is not designated 'usedAsFilename'.
Warning: file: /home/cwang85/maya/2020/prefs/filePathEditorRegistryPrefs.mel line 7: filePathEditor: Attribute 'aiVolume.filename' is invalid or is not designated 'usedAsFilename'.
Warning: line 1: filePathEditor: Attribute 'aiVolume.filename' and label 'VDB' have been saved already.
Warning: line 1: filePathEditor: Attribute 'aiImage.filename' and label 'Image' have been saved already.
Warning: line 1: filePathEditor: Attribute 'aiPhotometricLight.aiFilename' and label 'IES' have been saved already.
Successfully imported python module 'arnold'
Successfully imported python module 'mtoa'
root : ERROR : code for hash md5 was not found.
Traceback (most recent call last):
  File "/usr/autodesk/maya2020/lib/python27.zip/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/autodesk/maya2020/lib/python27.zip/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md5
root : ERROR : code for hash sha1 was not found.
Traceback (most recent call last):
  File "/usr/autodesk/maya2020/lib/python27.zip/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/autodesk/maya2020/lib/python27.zip/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha1
root : ERROR : code for hash sha224 was not found.
Traceback (most recent call last):
  File "/usr/autodesk/maya2020/lib/python27.zip/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/autodesk/maya2020/lib/python27.zip/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha224
root : ERROR : code for hash sha256 was not found.
Traceback (most recent call last):
  File "/usr/autodesk/maya2020/lib/python27.zip/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/autodesk/maya2020/lib/python27.zip/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha256
root : ERROR : code for hash sha384 was not found.
Traceback (most recent call last):
  File "/usr/autodesk/maya2020/lib/python27.zip/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/autodesk/maya2020/lib/python27.zip/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha384
root : ERROR : code for hash sha512 was not found.
Traceback (most recent call last):
  File "/usr/autodesk/maya2020/lib/python27.zip/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/autodesk/maya2020/lib/python27.zip/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha512
Successfully registered renderer 'arnold'
Error: line 1: RuntimeError: file <maya console> line 1: Plug-in, "vrayformaya", was not found on MAYA_PLUG_IN_PATH.
Warning: line 1: Unrecognized node type for node 'vraySettings'; preserving node information during this session.
Warning: line 1: Errors have occurred while reading this scene that may result in data loss.
File read in  11.6 seconds.
Result: /course/cs125_projects/elevator/elevator/sets/apartment_set/full_sets/Scene6_Shot2.mb
Warning: file: /usr/autodesk/maya2020/scripts/others/makeCameraRenderable.mel line 45: Found camera shot2Shape.
Warning: OpenSubdiv gets different edge topology to Maya poly.
Warning: Fail to create OpenSubdiv TopologyRefiner.
Warning: OpenSubdiv gets different edge topology to Maya poly.
Warning: Fail to create OpenSubdiv TopologyRefiner.
terminate called after throwing an instance of 'std::system_error'
  what():  Resource temporarily unavailable
Stack trace:
  gsignal
  abort
  /lib/x86_64-linux-gnu/libstdc++.so.6(+0x8c983) [0x147f01964983]
  /lib/x86_64-linux-gnu/libstdc++.so.6(+0x928c6) [0x147f0196a8c6]
  /lib/x86_64-linux-gnu/libstdc++.so.6(+0x92901) [0x147f0196a901]
  /lib/x86_64-linux-gnu/libstdc++.so.6(+0x92b34) [0x147f0196ab34]
  /lib/x86_64-linux-gnu/libstdc++.so.6(+0x8ea55) [0x147f01966a55]
  /usr/autodesk/maya2020/lib/libDependCommand.so(+0x2f719) [0x147f07f3f719]
  /usr/autodesk/arnold/maya2020/plug-ins/../bin/libai.so(+0x3acf38f) [0x147eac0ff38f]
  /usr/autodesk/arnold/maya2020/plug-ins/../bin/libai.so(+0x3aceaea) [0x147eac0feaea]
  /usr/autodesk/arnold/maya2020/plug-ins/../bin/libai.so(+0x3acd80b) [0x147eac0fd80b]
  /usr/autodesk/arnold/maya2020/plug-ins/../bin/libai.so(+0x3acd0b9) [0x147eac0fd0b9]
  /usr/autodesk/arnold/maya2020/plug-ins/../bin/libai.so(+0x3acbcb8) [0x147eac0fbcb8]
  /usr/autodesk/arnold/maya2020/plug-ins/../bin/libai.so(+0x3acbfd7) [0x147eac0fbfd7]
  /usr/autodesk/arnold/maya2020/plug-ins/../bin/libai.so(+0x3acc551) [0x147eac0fc551]
  /usr/autodesk/arnold/maya2020/plug-ins/../bin/libai.so(+0x3d0feb2) [0x147eac33feb2]
  /usr/autodesk/arnold/maya2020/plug-ins/../bin/libai.so(+0x3d10efa) [0x147eac340efa]
  /usr/autodesk/arnold/maya2020/plug-ins/../bin/libai.so(+0x3a76316) [0x147eac0a6316]
  /usr/autodesk/arnold/maya2020/plug-ins/../bin/libai.so(+0x3a73e1b) [0x147eac0a3e1b]
  /usr/autodesk/arnold/maya2020/plug-ins/../bin/libai.so(+0x3a83e75) [0x147eac0b3e75]
  /usr/autodesk/arnold/maya2020/plug-ins/../bin/libai.so(+0xc27abe) [0x147ea9257abe]
  /usr/autodesk/arnold/maya2020/plug-ins/../bin/libai.so(+0xf4c77b) [0x147ea957c77b]
  /lib/x86_64-linux-gnu/libpthread.so.0(+0x7fa3) [0x147f016d7fa3]
  clone
1Error: line 1: File contains unknown nodes or data.  To preserve this information, the current file type cannot be changed.
Fatal Error. Attempting to save in /tmp/2362579.1.long.q/cwang85.20201207.1516.ma
Error: line 1: File contains unknown nodes or data.  To preserve this information, the current file type cannot be changed.
Writing crash report in /tmp/2362579.1.long.q/cwang85.20201207.1516.crash
/usr/autodesk/maya2020/bin/maya: line 194: 11097 Segmentation fault      /usr/autodesk/maya2020/bin/maya.bin '-batch' '-file' '/course/cs125_projects/elevator/elevator/sets/apartment_set/full_sets/Scene6_Shot2.mb' '-script' '/tmp/2362579.1.long.q/ASTMPEEMmeL.mel'
// Maya exited with status 139
